#include <winver.h>
#include "../config.h"
#include "../lsmash.h"

#ifdef DEBUG
#define VER_DEBUG   VS_FF_DEBUG
#define VER_PRIVATE VS_FF_PRIVATEBUILD
#else
#define VER_DEBUG   0
#define VER_PRIVATE 0
#endif

#define VER_FILEVERSION           LSMASH_VERSION_MAJOR,LSMASH_VERSION_MINOR,LSMASH_VERSION_MICRO,LSMASH_REV_NUM
#define VER_STR_FILEVERSION      "rev" LSMASH_REV
#define VER_STR_COMMENTS         ""
#define VER_STR_COMPANYNAME      ""
#define VER_STR_FILEDESCRIPTION  CLI_EXE_FILENAME
#define VER_STR_INTERNALNAME     CLI_EXE_FILENAME
#define VER_STR_ORIGINALFILENAME CLI_EXE_FILENAME
#define VER_STR_LEGALCOPYRIGHT   "Copyright (C) 2010-2020 L-SMASH project"
#define VER_STR_PRODUCTNAME      "L-SMASH"
#define VER_PRODUCTVERSION       VER_FILEVERSION
#define VER_STR_PRODUCTVERSION   "rev" LSMASH_REV " " LSMASH_GIT_HASH
